import React, { useState } from 'react';

export default function ImageResultCard({ thought, imageData, prompt }) {
  const [expanded, setExpanded] = useState(false);

  const handleDownload = () => {
    const a = document.createElement('a');
    a.href = imageData;
    a.download = 'sierra-generated.png';
    a.click();
  };

  return (
    <div className="image-card">
      <div className="image-card-thought">
        <span>💭</span>
        <span>{thought}</span>
      </div>

      <div className={`image-card-frame ${expanded ? 'expanded' : ''}`}>
        <img
          src={imageData}
          alt="Generated by Copilot"
          className="image-card-img"
          onClick={() => setExpanded((v) => !v)}
        />
        {!expanded && (
          <div className="image-card-overlay" onClick={() => setExpanded(true)}>
            Click to expand
          </div>
        )}
      </div>

      <div className="image-card-prompt">{prompt}</div>

      <div className="image-card-actions">
        <button className="img-btn img-btn-download" onClick={handleDownload}>
          ↓ Download
        </button>
        <button className="img-btn img-btn-expand" onClick={() => setExpanded((v) => !v)}>
          {expanded ? '↙ Collapse' : '↗ Expand'}
        </button>
      </div>
    </div>
  );
}
